### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by ahmed-bashir-ms** [Yadentra/selenium-pytest-automation#1]
**This is a Feedback, you can close this issue after incorporating the feedback.**

1. **test_google_search.py**
   - At the end of the script, you are halting the script for 5 minutes which is too much. Please remove this or decrease it to a couple of seconds. 
2. **test_register_user.py**
    - Script starts fine. After navigating to the **signup/login** page, it correctly enters the username for registration but for the email the locator being used targets the email address field in the login from not in the registration form due to which rest of the test cannot be run. Please correct it so that the `xpath` targets the email field from the registration form and not the login form. 
    - After correcting the locator, make sure that rest of the registration form populates correctly. As I have corrected the locator for the step above to test the rest of the script but unfortunately it is not populating the data, which means you need to recheck all the locators.
    - Also, decrease the `time.sleep`.
3. **test_search_product.py**
    - Script is not working. It opens the website and halts there. Please review this script.

**Comment by Yadentra** [comment]
Okay . Thank you, on it
